export const initialCreateItemSoal={
        idbaris:0,
        fase_jenjang:[],
        jenjang_khusus:0,
        kurikulum:'kurmer',
        kode_mapel:'',
        mapel_name:'',
        kd_id:0,
        kd_deskripsi:'',
        bentuk_soal:'',
        materi_pokok:'',
        indikator_soal:'',
        lk:'',
        ruang_lingkup:'',
        stimulus:'',
        pertanyaan:'',
        jawaban:[],//string|number|string[]|number[],
        pembahasan_penskoran:'',//string,
        // json_alat_jawab?:PgTunggal|PgKompleks|PilihanBenarSalahType|PilihanMenjodohkan,
        // snapshot_kurikulum:propertyKuriklum,
        oleh:'',
        refrensi:'',
        auto_koreksi:'',
        status:''
    }